name: my_shop_appp
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  cached_network_image: ^3.3.0 
  shared_preferences: ^2.0.9
  flutter_blue_plus: ^1.18.0
  flutter_local_notifications: ^19.0.0 
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/image1.jpg
    - assets/images/club_articles.jpg
    - assets/images/distillery.jpg
    - assets/images/gifts.jpg
    - assets/images/gin.jpg
    - assets/images/rum.jpg
    - assets/images/spirits.jpg
    - assets/images/whisky.jpg
    - assets/images/placeholder.jpg
    - assets/images/login_illustration.png
    - assets/images/Register-bro.png
  uses-material-design: true
